### ISSUE TITLE
Execution could not continue error

### ISSUE THREAD

**Issue by gameuser1982** [ajantaju/br_vr#2]
I'm using Fishbiter's GZ3Doom fork to play Doom in VR on my Vive. 
It's the March 1st build here: https://github.com/Fishbiter/gz3doom/releases

Although brutal doom works fine on its own as do the included VR 3D models with Fishbiter's build (WeaponsForVR.pk3), your brutal doom VR models don't seem to work. What am I doing wrong? I downloaded BR_VR_pbr_RC1.zip and renamed it to BR_VR_pbr_RC1.pk3

Then I launch gz3doom like this:

gzdoom.exe -file brutalv21.pk3 BR_VR_pbr_RC1.pk3

I also tried launching gz3doom like this:

gzdoom.exe -file brutalv21.pk3 -file BR_VR_pbr_RC1.pk3

In both cases I get the following error:

Execution could not continue.

Script error, "BR_VR_pbr_RC1.zip:weapons.gl" line 1:
Error parsing defs.  Unknown tag: material.

What am I doing wrong here?

**Comment by ajantaju** [comment]
Use newer version: https://github.com/hh79/gzdoomvr/releases
