### ISSUE TITLE
Weapon Pickups

### ISSUE THREAD

**Issue by somerandomaussie** [ajantaju/br_vr#3]
Wondering how to make BD weapon pickups 3d models? 
The only one that works for me in the latest update is the flamethrower. 
I know some of the weapon pickups were 3d models in an older version but not all of them. 
Is this in the pipeline or am i doing something wrong?

**Comment by ajantaju** [comment]
I removed the 3d pickup models that i tested for the rifle and the pistol. They looked kind of silly IMO, rotating there. And i had an issue with the shotgun pickup showing both the 3d model and the 2d sprite.
