### ISSUE TITLE
Just not working

### ISSUE THREAD

**Issue by snikabarz** [ajantaju/br_vr#4]
Not sure if anyone's going to respond to this but it's worth a shot. I just downloaded this, put the zip in my VR GZDoom folder, added the lines needed in the bat file listed in the description, I boot it up and it just doesn't work. The weapons are just sprites, no models

**Comment by PlanetOrca** [comment]
You have to extract the zip -_-

**Comment by snikabarz** [comment]
> 
> 
> You have to extract the zip -_-

No you don't, it literally says in the example to type in the .bat "BR_VR_b1.zip" to find the mod. Plus I got it working, the example for what to write in the .bat had a slightly different version of brutal doom so it wasn't starting. and it is still in the zip
