### ISSUE TITLE
Crashes when using brutalv21.10.2.pk3

### ISSUE THREAD

**Issue by Dos-Boss** [ajantaju/br_vr#6]
Can't get this to run on the latest community patched version of BD21 (brutalv21.10.2.pk3)
Lots of unknown class name errors stopping launch.

This version runs a lot nicer in VR compared to the standard brutalv21.pk3 (berserk screen tint works properly, no black box when entering a level etc)

**Comment by BLOODWOLF333** [comment]
I have forked from this repo and am currently working on updating this to work with v21.11.3
