### ISSUE TITLE
WolfenDOOM VR Weapons

### ISSUE THREAD

**Issue by codeflorist** [ajantaju/br_vr#9]
hey ajantaju! first of all many thanks for your awesome VR weapons!

i've taken the liberty to create a weapon-pack for WolfenDOOM by cannibalizing your Brutal Wolfenstein pack (using the Knife, Luger, MP40 and MG42). i've uploaded the file here:
https://www.mediafire.com/file/d35yqagdhpeny9m/WolfenDOOM_3D_VR_Weapons.pk3/file

feel free to add it to to your repository for others to download!

i'm using these weapons with [WolfenDoom Enhanced](https://www.moddb.com/mods/wolfendoom/downloads/wolfendoom-enhanced) and it's [Hi res music and textures pack](https://www.moddb.com/mods/wolfendoom/addons/wolfendoom-enhanced-hi-res-music-and-textures) (both by [TheArmyGuy](https://www.moddb.com/members/the-army-guy))

**Comment by ajantaju** [comment]
Sure, i'll upload it to github soon.
